### ISSUE TITLE
Epic Index: Turn Tessa into a client-side only gem & decomission Tessa service

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/tessa#27]
The Tessa service was very useful back in the days before ActiveStorage, but now ActiveStorage is the Rails best practice way to do things and comes batteries-included with Rails 7.

Rework the Tessa gem so that it no longer uploads to the Tessa service, but rather uploads/downloads directly to s3 via ActiveStorage.  Clients would no longer have Tessa username/password credentials, but rather AWS s3 access credentials.

Then kill the Tessa app in Heroku.

- [x] 1. Rework the Tessa gem so that it acts as a wrapper around ActiveStorage for new uploads, w/ fallback to the Tessa service for missing images.
    - [x] Gem: https://github.com/watermarkchurch/tessa-client/issues/15
    - [x] Events system: https://github.com/watermarkchurch/events/issues/459
    - [x] Media System https://github.com/watermarkchurch/media/issues/489
    - [x] Watermark Resources https://github.com/watermarkchurch/watermarkresources.com/issues/1636
    - [x] JTJ-CMS https://github.com/watermarkchurch/jtj-cms/issues/455
- [x] 2. Run a migration in an ActiveRecord job on each downstream client app that creates ActiveStorage records in the client app's Postgres for all old tessa uploads
    - [x] Events System: https://github.com/watermarkchurch/events/issues/460
    -  ~~Media System~~ this is unnecessary
    - [x] Watermark Resources https://github.com/watermarkchurch/watermarkresources.com/issues/1702
    - [x] JTJ-CMS https://github.com/watermarkchurch/jtj-cms/issues/470

- [x] 3. Remove fallback to Tessa service (perhaps by just removing the TESSA_URL env var?) and test that all old assets still resolve
    - [x] Events System https://github.com/watermarkchurch/events/issues/562
    - [x] Media System https://github.com/watermarkchurch/media/issues/527
    - [x] Watermark Resources https://github.com/watermarkchurch/watermarkresources.com/issues/1719
    - [x] JTJ-CMS https://zube.io/watermarkchurch/development/c/12438
    - [x] Gem: https://github.com/watermarkchurch/tessa-client/issues/16

- [x] 4. Decommision Tessa
    - [x] Turn off the Tessa service https://github.com/watermarkchurch/tessa/issues/49
    - [ ] Archive and decommission the Tessa repo https://github.com/watermarkchurch/tessa/issues/50

- [ ] 5. Cleanup
  - [ ] Clean up old tessa assets (#51)
  - [ ] Remove duplicate assets from media-files.watermark.org (https://github.com/watermarkchurch/media/issues/539)

**Comment by jpowell** [comment]
Could we potentially consider using something like cloudinary instead?

https://cloudinary.com/

**Comment by gburgett** [comment]
Cloudinary would be great as a backend to ActiveStorage.  I'd like to move this as close to the "official path" for Rails apps as possible.
